version: '3.8'

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"            # LocalStack Gateway
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      DEBUG: 1
      SERVICES: lambda,apigateway,s3,cloudfront,iam,bedrock
      DATA_DIR: /tmp/localstack/data
      DOCKER_HOST: unix:///var/run/docker.sock
      HOST_TMP_FOLDER: ${TMPDIR:-/tmp/}localstack
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack

networks:
  localstack:
    driver: bridge